Proposed amendment on html/css file
zeff96/Personal-Portfolio pull request #1
Opened 2023-01-12 14:45 UTC by zeff96

Add HTML, CSS, readme, and license to the document.

I have created the HTML page on this branch, and styled all its children with the relevant CSS properties, equally I have updated the readme file to a professional level and added a license to the document.

2023-01-12 16:20 UTC, tufoinnkuo10 requested changes
Hi @zeff96 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally


Required Changes ♻️ 
Check the comments under the review
![tufoin](https://media.giphy.com/media/ksPoGhnZvHP4QoYT1m/giphy.gif)

Optional suggestions
NB - [optional] please do not push commits to the main branch, instead the main branch will be updated when the feature branch has been approved and merged to it. This will help the reviewer see all your changes in the feature branch. nice work

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-01-12 16:20 UTC, tufoinnkuo10 commented on index.html
> +          my logo
- [x] kindly ensure that your logo has a link (a tag).

This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info.

2023-01-12 16:20 UTC, tufoinnkuo10 commented on index.html
> +    <nav class="top-nav">
- [ ] i can see you have two nav's . please kindly use just the nav for the hamburger icon. The `nav` tag is for semantics reason

2023-01-12 16:20 UTC, tufoinnkuo10 commented on index.html
> +  <header class="header">
- [ ] please kindly ensure that the header tag covers just the tool bar section. the headline section will be covered by the `section tag`. the `header` tag is used as a page header, it contains the site's title or logo (or both) and the main site navigation. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) for more info.

2023-01-12 16:20 UTC, tufoinnkuo10 commented on index.html
> +      <header class="text-section">
- [ ] kindly use a div tag here instead of a header tag.a header tag is used as a page header

2023-01-12 16:20 UTC, tufoinnkuo10 commented on index.html
> +            <a href=""><i class="fa-brands fa-angellist fa-2x angellist"></i></a>
- [ ] please kindly ensure that The list of icons uses a `ul` tag to group them, and `li` per icon;

2023-01-12 16:20 UTC, tufoinnkuo10 commented on index.html
> +          I&#8217;m Adeka Glad to see you!
- [ ] nice job. please kindly add a background image not only to make it look like the figma version, but also to make it look beautiful and presentable. nice work

yours
![Screenshot (741)](https://user-images.githubusercontent.com/65298048/212117214-f1d854b5-5d3f-47e3-87f6-8db7bf7da1a8.png)
figma version
![Screenshot (742)](https://user-images.githubusercontent.com/65298048/212117464-ae4aea5f-aeca-44a0-bd35-6f2150ed327b.png)

2023-01-12 16:20 UTC, tufoinnkuo10 commented on index.html
> +        </p>
- [ ] nice work. Please make your work responsive until the desktop screen size
![Screenshot (743)_LI](https://user-images.githubusercontent.com/65298048/212120028-0f660cbb-736a-49f0-abb8-e7b4c03d0154.jpg)

2023-01-12 16:53 UTC, zeff96 commented on index.html
> +          my logo
@tufoinnkuo10 Thanks, the issue closed

2023-01-13 04:30 UTC, Shedrack-Sunday approved these changes
Hi @zeff96 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.tenor.com/7k0Eh3Jwg1MAAAAM/approved-stamp-of-approval.gif)

## Highlights 🏴 
 
-  [ ] Linters are passing 💯 
-  [ ] Right commit messages 🍸 
-  [ ] Proper Gitflow ✔️ 
-  [ ] Great UX design
-  Proper Use of README file

## Optional suggestions

- [ ] I suggest you always use a descriptive branch name for your projects. `Portfolio-Feature-CSS-HTML` sounds a lot more descriptive than `HTML/CSS` which is too genric. Kindly take note of future projects. Well done 👏  

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 06:54 UTC, zeff96 commented
@Shedrack-Sunday Thanks for the advise not taken, going forward i will use a descriptive branch name as suggested

2023-01-13 06:58 UTC, merged